version: "3"
services:
  influxdb:
    image: influxdb
    volumes:
      - influxdb_data:/var/lib/influxdb/data
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=PGRacingTeamTelemetry
      - DOCKER_INFLUXDB_INIT_ORG=PGRacingTeam
      - DOCKER_INFLUXDB_INIT_BUCKET=telemetry
    ports:
      - "8086:8086"
  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana/data
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
  websocket_server:
    image: websocket_server
    ports:
      - "1627:1627"
  redis:
    image: redis
    ports:
      - 6379:6379
volumes:
  influxdb_data: {}
  grafana_data: {}
  redis_data: 
    driver: local 