version: "3"
services:
  influxdb:
    image: influxdb
    volumes:
      - influxdb_data:/var/lib/influxdb/data
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=pgracing
      - DOCKER_INFLUXDB_INIT_BUCKET=telemetry
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=token
    ports:
      - "8086:8086"
  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana/data
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
volumes:
  influxdb_data: {}
  grafana_data: {}