{
 "title": "Lap comparator 2023-11-05",
 "time": { "from": "2023-11-05T06:00:00.000Z", "to": "2023-11-05T10:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "TimeShift", "query": "120s" },
   { "name": "bucketName", "query": "telemetry-2023-11-05" },
   { "name": "lap1", "label": "first lap number", "query": "14" },
   { "name": "lap2", "label": "second lap number", "query": "31" }
  ]
 },
 "panels": [
  {
   "title": "First Lap Map",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "\r\nstart_time_row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._value == int(v: ${lap1}))\r\n  |> first()\r\n  |> keep(columns: [\"_time\"])\r\n  |> findRecord(idx: 0, fn: (key) => true)\r\n\r\nfinish_time_row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._value == int(v: ${lap1}))\r\n  |> last()\r\n  |> keep(columns: [\"_time\"])\r\n  |> findRecord(idx: 0, fn: (key) => true)\r\n\r\n\r\nfrom(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: start_time_row._time, stop: finish_time_row._time)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gps\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"gps_position\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Second Lap Map",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 14, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "query": "start_time_row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._value == int(v: ${lap2}))\r\n  |> first()\r\n  |> keep(columns: [\"_time\"])\r\n  |> findRecord(idx: 0, fn: (key) => true)\r\n\r\nfinish_time_row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._value == int(v: ${lap2}))\r\n  |> last()\r\n  |> keep(columns: [\"_time\"])\r\n  |> findRecord(idx: 0, fn: (key) => true)\r\n\r\n\r\nfrom(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: start_time_row._time, stop: finish_time_row._time)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gps\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"gps_position\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "First Lap - suspension travel [mm]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "query": "start_time_row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._value == int(v: ${lap1}))\r\n  |> first()\r\n  |> keep(columns: [\"_time\"])\r\n  |> findRecord(idx: 0, fn: (key) => true)\r\n\r\nfinish_time_row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._value == int(v: ${lap1}))\r\n  |> last()\r\n  |> keep(columns: [\"_time\"])\r\n  |> findRecord(idx: 0, fn: (key) => true)\r\n\r\n\r\nfrom(bucket: \"${bucketName}\")\r\n  |> range(start: start_time_row._time, stop: finish_time_row._time)\r\n  |> filter(fn: (r) => r[\"ID\"] == \"7\" or r[\"ID\"] == \"8\" or r[\"ID\"] == \"11\" or r[\"ID\"] == \"12\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)\r\n"
    }
   ]
  },
  {
   "title": "Second lap - suspension travel [mm]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "query": "start_time_row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._value == int(v: ${lap2}))\r\n  |> first()\r\n  |> keep(columns: [\"_time\"])\r\n  |> findRecord(idx: 0, fn: (key) => true)\r\n\r\nfinish_time_row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._value == int(v: ${lap2}))\r\n  |> last()\r\n  |> keep(columns: [\"_time\"])\r\n  |> findRecord(idx: 0, fn: (key) => true)\r\n\r\n\r\nfrom(bucket: \"${bucketName}\")\r\n  |> range(start: start_time_row._time, stop: finish_time_row._time)\r\n  |> filter(fn: (r) => r[\"ID\"] == \"7\" or r[\"ID\"] == \"8\" or r[\"ID\"] == \"11\" or r[\"ID\"] == \"12\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "First Lap - Steering wheel angle [deg]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "start_time_row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._value == int(v: ${lap1}))\r\n  |> first()\r\n  |> keep(columns: [\"_time\"])\r\n  |> findRecord(idx: 0, fn: (key) => true)\r\n\r\nfinish_time_row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._value == int(v: ${lap1}))\r\n  |> last()\r\n  |> keep(columns: [\"_time\"])\r\n  |> findRecord(idx: 0, fn: (key) => true)\r\n\r\n\r\nfrom(bucket: \"${bucketName}\")\r\n  |> range(start: start_time_row._time, stop: finish_time_row._time)\r\n\t|> filter(fn: (r) => r[\"ID\"] == \"6\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Second Lap - Steering wheel angle [deg]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "start_time_row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._value == int(v: ${lap2}))\r\n  |> first()\r\n  |> keep(columns: [\"_time\"])\r\n  |> findRecord(idx: 0, fn: (key) => true)\r\n\r\nfinish_time_row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._value == int(v: ${lap2}))\r\n  |> last()\r\n  |> keep(columns: [\"_time\"])\r\n  |> findRecord(idx: 0, fn: (key) => true)\r\n\r\n\r\nfrom(bucket: \"${bucketName}\")\r\n  |> range(start: start_time_row._time, stop: finish_time_row._time)\r\n\t|> filter(fn: (r) => r[\"ID\"] == \"6\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "First Lap - Speed [kmph]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "start_time_row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._value == int(v: ${lap1}))\r\n  |> first()\r\n  |> keep(columns: [\"_time\"])\r\n  |> findRecord(idx: 0, fn: (key) => true)\r\n\r\nfinish_time_row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._value == int(v: ${lap1}))\r\n  |> last()\r\n  |> keep(columns: [\"_time\"])\r\n  |> findRecord(idx: 0, fn: (key) => true)\r\n\r\n\r\nfrom(bucket: \"${bucketName}\")\r\n  |> range(start: start_time_row._time, stop: finish_time_row._time)\r\n\t|> filter(fn: (r) => r[\"_measurement\"] == \"gps\" or r[\"_measurement\"] == \"abs\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"gps_position\" or r[\"ID\"] == \"5\" or r[\"ID\"] == \"4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Second Lap - Speed [kmph]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "start_time_row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._value == int(v: ${lap2}))\r\n  |> first()\r\n  |> keep(columns: [\"_time\"])\r\n  |> findRecord(idx: 0, fn: (key) => true)\r\n\r\nfinish_time_row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._value == int(v: ${lap2}))\r\n  |> last()\r\n  |> keep(columns: [\"_time\"])\r\n  |> findRecord(idx: 0, fn: (key) => true)\r\n\r\n\r\nfrom(bucket: \"${bucketName}\")\r\n  |> range(start: start_time_row._time, stop: finish_time_row._time)\r\n\t|> filter(fn: (r) => r[\"_measurement\"] == \"gps\" or r[\"_measurement\"] == \"abs\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"gps_position\" or r[\"ID\"] == \"5\" or r[\"ID\"] == \"4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  }
 ]
}