{
 "title": "Telemetry 2023-11-05 2",
 "time": { "from": "2023-11-05T08:02:36.609Z", "to": "2023-11-05T08:37:22.833Z" },
 "templating": {
  "list": [
   { "name": "bucketName", "query": "telemetry-2023-11-05" }
  ]
 },
 "panels": [
  {
   "title": "Map",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 23, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gps\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"gps_position\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Steering wheel angle [deg]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"ID\"] == \"6\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Dampers - suspension travel [mm]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"ID\"] == \"7\" or r[\"ID\"] == \"8\" or r[\"ID\"] == \"11\" or r[\"ID\"] == \"12\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Accelerometer [m/s^2]",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-rb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"acc\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"acc_x\" or r[\"_field\"] == \"acc_y\" or r[\"_field\"] == \"acc_z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Speed [kmph]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gps\" or r[\"_measurement\"] == \"abs\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"gps_position\" or r[\"ID\"] == \"5\" or r[\"ID\"] == \"4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Speed [km/h]",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 10, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-rb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"spd\")\r\n  |> filter(fn: (r) => r[\"Record\"] == \"velocity\" or r[\"Record\"] == \"velocity_x\" or r[\"Record\"] == \"velocity_y\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\" or r[\"_field\"] == \"speed_x\" or r[\"_field\"] == \"speed_y\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Angular velocity [deg/s]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "rotdegs" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-rb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gyro\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gyro_x\" or r[\"_field\"] == \"gyro_y\" or r[\"_field\"] == \"gyro_z\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Angular acceleration [deg/s^2]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "°/s^2" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-rb\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"angular_acc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ang_acc_x\" or r[\"_field\"] == \"ang_acc_y\" or r[\"_field\"] == \"ang_acc_z\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  }
 ]
}