{
 "title": "Telemetry",
 "time": { "from": "2023-11-04T00:00:03.952Z", "to": "2023-11-04T00:00:33.445Z" },
 "panels": [
  {
   "title": "Map",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 23, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gps\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"gps_position\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Steering wheel angle [deg]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"ID\"] == \"6\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Dampers - suspension travel [mm]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"ID\"] == \"7\" or r[\"ID\"] == \"8\" or r[\"ID\"] == \"11\" or r[\"ID\"] == \"12\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Speed [kmph]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gps\" or r[\"_measurement\"] == \"abs\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"gps_position\" or r[\"ID\"] == \"5\" or r[\"ID\"] == \"4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  }
 ]
}