{
 "title": "Telemetry 2023-11-05-Racebox",
 "time": { "from": "2023-11-04T23:00:00.000Z", "to": "2023-11-05T22:59:59.000Z" },
 "panels": [
  {
   "title": "Map",
   "type": "geomap",
   "gridPos": { "h": 18, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gps\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\r\n\r\n|> pivot(columnKey: [\"_field\"], rowKey: [\"_time\"], valueColumn: \"_value\")\r\n\r\n|> duplicate(column: \"latitude\", as: \"lat\")\r\n|> duplicate(column: \"longitude\", as: \"lon\")\r\n"
    }
   ]
  },
  {
   "title": "GPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gps\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"gps_position\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Accelerometer [m/s^2]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"acc\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"acc_x\" or r[\"_field\"] == \"acc_y\" or r[\"_field\"] == \"acc_z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Gyro [deg/s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "rotdegs" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gyro\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gyro_x\" or r[\"_field\"] == \"gyro_y\" or r[\"_field\"] == \"gyro_z\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Speed [km/h]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"spd\")\r\n  |> filter(fn: (r) => r[\"Record\"] == \"velocity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  }
 ]
}