{
 "title": "2023-11-05 Telemetry",
 "tags": [
  "Pszczółki",
  "PGR_07"
 ],
 "time": { "from": "2023-11-05T08:41:24.670Z", "to": "2023-11-05T08:47:13.682Z" },
 "templating": {
  "list": [
   { "name": "bucketName", "query": "telemetry-2023-11-05" },
   { "name": "bucketName2", "query": "telemetry-2023-11-05-Racebox" }
  ]
 },
 "panels": [
  {
   "title": "Map",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gps\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"gps_position\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Timer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lap_times\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"best_lap_number\" or r[\"_field\"] == \"best_time\" or r[\"_field\"] == \"lap_counter\" or r[\"_field\"] == \"last_time\")\r\n  |> filter(fn: (r) => r[\"lap_time\"] == \"best\" or r[\"lap_time\"] == \"best_lap_number\" or r[\"lap_time\"] == \"lap_number\" or r[\"lap_time\"] == \"last\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "KIlometrs Driven",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName2}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gps\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"total2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"km_driven\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Steering wheel angle [deg]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"angle\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "damp rebound - front left",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "total_number = () => {\r\n  row = from(bucket: \"${bucketName}\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n    |> filter(fn: (r) => r[\"_field\"] == \"position_rebound\")\r\n    |> filter(fn: (r) => r[\"ID\"] == \"7\")\r\n    |> count()  \r\n    |> last() \r\n    |> findRecord(fn: (key) => true, idx:0)\r\n  return float(v: row._value)\r\n    \r\n}\r\n\r\n\r\nfrom(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"position_rebound\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"7\")\r\n  |> duplicate(column: \"_value\", as: \"new_column\")\r\n  |> group(columns: [\"new_column\"])\r\n  |> count()\r\n  |> map(fn: (r) => ({r with _value: float(v: r._value) /total_number() * 100.0}))\r\n"
    }
   ]
  },
  {
   "title": "damp rebound - front right",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "total_number = () => {\r\n  row = from(bucket: \"${bucketName}\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n    |> filter(fn: (r) => r[\"_field\"] == \"position_rebound\")\r\n    |> filter(fn: (r) => r[\"ID\"] == \"8\")\r\n    |> count()  \r\n    |> last() \r\n    |> findRecord(fn: (key) => true, idx:0)\r\n  return float(v: row._value)\r\n    \r\n}\r\n\r\n\r\nfrom(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"position_rebound\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"8\")\r\n  |> duplicate(column: \"_value\", as: \"new_column\")\r\n  |> group(columns: [\"new_column\"])\r\n  |> count()\r\n  |> map(fn: (r) => ({r with _value: float(v: r._value) /total_number() * 100.0}))\r\n"
    }
   ]
  },
  {
   "title": "damp rebound - rear left",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "total_number = () => {\r\n  row = from(bucket: \"${bucketName}\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n    |> filter(fn: (r) => r[\"_field\"] == \"position_rebound\")\r\n    |> filter(fn: (r) => r[\"ID\"] == \"11\")\r\n    |> count()  \r\n    |> last() \r\n    |> findRecord(fn: (key) => true, idx:0)\r\n  return float(v: row._value)\r\n    \r\n}\r\n\r\n\r\nfrom(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"position_rebound\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"11\")\r\n  |> duplicate(column: \"_value\", as: \"new_column\")\r\n  |> group(columns: [\"new_column\"])\r\n  |> count()\r\n  |> map(fn: (r) => ({r with _value: float(v: r._value) /total_number() * 100.0}))\r\n"
    }
   ]
  },
  {
   "title": "damp rebound - rear left",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "total_number = () => {\r\n  row = from(bucket: \"${bucketName}\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n    |> filter(fn: (r) => r[\"_field\"] == \"position_rebound\")\r\n    |> filter(fn: (r) => r[\"ID\"] == \"12\")\r\n    |> count()  \r\n    |> last() \r\n    |> findRecord(fn: (key) => true, idx:0)\r\n  return float(v: row._value)\r\n    \r\n}\r\n\r\n\r\nfrom(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"position_rebound\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"12\")\r\n  |> duplicate(column: \"_value\", as: \"new_column\")\r\n  |> group(columns: [\"new_column\"])\r\n  |> count()\r\n  |> map(fn: (r) => ({r with _value: float(v: r._value) /total_number() * 100.0}))\r\n"
    }
   ]
  },
  {
   "title": "damp bump - front left",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "total_number = () => {\r\n  row = from(bucket: \"${bucketName}\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n    |> filter(fn: (r) => r[\"_field\"] == \"position_bump\")\r\n    |> filter(fn: (r) => r[\"ID\"] == \"7\")\r\n    |> count()  \r\n    |> last() \r\n    |> findRecord(fn: (key) => true, idx:0)\r\n  return float(v: row._value)\r\n    \r\n}\r\n\r\n\r\nfrom(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"position_bump\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"7\")\r\n  |> duplicate(column: \"_value\", as: \"new_column\")\r\n  |> group(columns: [\"new_column\"])\r\n  |> count()\r\n  |> map(fn: (r) => ({r with _value: float(v: r._value) /total_number() * 100.0}))\r\n"
    }
   ]
  },
  {
   "title": "damp bump - front right",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 11, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "total_number = () => {\r\n  row = from(bucket: \"${bucketName}\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n    |> filter(fn: (r) => r[\"_field\"] == \"position_bump\")\r\n    |> filter(fn: (r) => r[\"ID\"] == \"8\")\r\n    |> count()  \r\n    |> last() \r\n    |> findRecord(fn: (key) => true, idx:0)\r\n  return float(v: row._value)\r\n    \r\n}\r\n\r\n\r\nfrom(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"position_bump\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"8\")\r\n  |> duplicate(column: \"_value\", as: \"new_column\")\r\n  |> group(columns: [\"new_column\"])\r\n  |> count()\r\n  |> map(fn: (r) => ({r with _value: float(v: r._value) /total_number() * 100.0}))\r\n"
    }
   ]
  },
  {
   "title": "damp bump - rear left",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "total_number = () => {\r\n  row = from(bucket: \"${bucketName}\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n    |> filter(fn: (r) => r[\"_field\"] == \"position_bump\")\r\n    |> filter(fn: (r) => r[\"ID\"] == \"11\")\r\n    |> count()  \r\n    |> last() \r\n    |> findRecord(fn: (key) => true, idx:0)\r\n  return float(v: row._value)\r\n    \r\n}\r\n\r\n\r\nfrom(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"position_bump\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"11\")\r\n  |> duplicate(column: \"_value\", as: \"new_column\")\r\n  |> group(columns: [\"new_column\"])\r\n  |> count()\r\n  |> map(fn: (r) => ({r with _value: float(v: r._value) /total_number() * 100.0}))\r\n"
    }
   ]
  },
  {
   "title": "damp bump - rear right",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 11, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "total_number = () => {\r\n  row = from(bucket: \"${bucketName}\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n    |> filter(fn: (r) => r[\"_field\"] == \"position_bump\")\r\n    |> filter(fn: (r) => r[\"ID\"] == \"11\")\r\n    |> count()  \r\n    |> last() \r\n    |> findRecord(fn: (key) => true, idx:0)\r\n  return float(v: row._value)\r\n    \r\n}\r\n\r\n\r\nfrom(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"position_bump\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"11\")\r\n  |> duplicate(column: \"_value\", as: \"new_column\")\r\n  |> group(columns: [\"new_column\"])\r\n  |> count()\r\n  |> map(fn: (r) => ({r with _value: float(v: r._value) /total_number() * 100.0}))\r\n"
    }
   ]
  },
  {
   "title": "Acceleration [m/s^2]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"acc\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"acc_x\" or r[\"_field\"] == \"acc_y\" or r[\"_field\"] == \"acc_z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Dampers - suspension travel [mm]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"ID\"] == \"7\" or r[\"ID\"] == \"8\" or r[\"ID\"] == \"11\" or r[\"ID\"] == \"12\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"angle\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Angular velocity [deg/s]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "rotdegs" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gyro\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gyro_x\" or r[\"_field\"] == \"gyro_y\" or r[\"_field\"] == \"gyro_z\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Dampers - suspension travel speed [mm/s]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "mm/s" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"ID\"] == \"7\" or r[\"ID\"] == \"8\" or r[\"ID\"] == \"11\" or r[\"ID\"] == \"12\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"velocity\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Angular acceleration [deg/sec^2]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "°/sec^2" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"angular_acc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ang_acc_x\" or r[\"_field\"] == \"ang_acc_y\" or r[\"_field\"] == \"ang_acc_z\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Speed [kmph]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gps\" or r[\"_measurement\"] == \"abs\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"gps_position\" or r[\"ID\"] == \"5\" or r[\"ID\"] == \"4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Rotation angles [deg]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"angles\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pitch_angle\" or r[\"_field\"] == \"roll_angle\" or r[\"_field\"] == \"yaw_angle\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Speed [km/h]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"spd\")\r\n  |> filter(fn: (r) => r[\"Record\"] == \"velocity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Velocity [km/h]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vel_acc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vel_x\" or r[\"_field\"] == \"vel_y\" or r[\"_field\"] == \"vel_z\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  }
 ]
}