{
 "title": "2024-03-09 racebox & cooling system",
 "tags": [
  "Pszczółki",
  "PGR_07"
 ],
 "time": { "from": "2024-03-09T10:00:00.000Z", "to": "2024-03-09T14:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "bucketName", "query": "telemetry-2024-03-09" }
  ]
 },
 "panels": [
  {
   "title": "Map",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gps\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"gps_position\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Timer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lap_times\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"best_lap_number\" or r[\"_field\"] == \"best_time\" or r[\"_field\"] == \"lap_counter\" or r[\"_field\"] == \"last_time\")\r\n  |> filter(fn: (r) => r[\"lap_time\"] == \"best\" or r[\"lap_time\"] == \"best_lap_number\" or r[\"lap_time\"] == \"lap_number\" or r[\"lap_time\"] == \"last\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Kilometrs Driven",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gps\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"total2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"km_driven\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Average acceleration per lap (only turns)",
   "type": "trend",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"forcex\" or r[\"_measurement\"] == \"forcey\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lap_number\" or r[\"_field\"] == \"mean_force_x\" or r[\"_field\"] == \"mean_force_y\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\")"
    }
   ]
  },
  {
   "title": "Acceleration [m/s^2]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"acc\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"acc_x\" or r[\"_field\"] == \"acc_y\" or r[\"_field\"] == \"acc_z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Average velocity per lap",
   "type": "trend",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"spd\")\r\n  |> filter(fn: (r) => r[\"avg\"] == \"speed\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lap_number\" or r[\"_field\"] == \"mean_speed\")"
    }
   ]
  },
  {
   "title": "Speed [km/h]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"spd\")\r\n  |> filter(fn: (r) => r[\"Record\"] == \"velocity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Angular velocity [deg/s]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "rotdegs" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gyro\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gyro_x\" or r[\"_field\"] == \"gyro_y\" or r[\"_field\"] == \"gyro_z\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Velocity [km/h]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vel_acc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vel_x\" or r[\"_field\"] == \"vel_y\" or r[\"_field\"] == \"vel_z\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Angular acceleration [deg/sec^2]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "°/sec^2" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"angular_acc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ang_acc_x\" or r[\"_field\"] == \"ang_acc_y\" or r[\"_field\"] == \"ang_acc_z\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Engine and Radiators Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"in\" or r[\"_field\"] == \"out\")\r\n  |> filter(fn: (r) => r[\"temperature\"] == \"engine\" or r[\"temperature\"] == \"radiator_l\" or r[\"temperature\"] == \"radiator_r\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Rotation angles [deg]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"angles\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pitch_angle\" or r[\"_field\"] == \"roll_angle\" or r[\"_field\"] == \"yaw_angle\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "MAP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 46 },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"engine\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"MAP\")\r\n  |> filter(fn: (r) => r[\"engine\"] == \"raw\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Engine and Radiator Temperature Delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"delta\")\r\n  |> filter(fn: (r) => r[\"temperature\"] == \"engine\" or r[\"temperature\"] == \"radiator_l\" or r[\"temperature\"] == \"radiator_r\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Temperature Rise Velocity [°C/min]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "°C/min" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"in_delta7\" or r[\"_field\"] == \"out_delta7\")\r\n  |> filter(fn: (r) => r[\"temperature\"] == \"engine\" or r[\"temperature\"] == \"radiator_l\" or r[\"temperature\"] == \"radiator_r\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Heat to cooling system [kJ/s]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "kJ/s" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"engine\" or r[\"_measurement\"] == \"temp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"heat_from_engine\" or r[\"_field\"] == \"heat_theoretical\")\r\n  |> filter(fn: (r) => r[\"engine\"] == \"heat\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Engine RPM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 62 },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"engine\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RPM\")\r\n  |> filter(fn: (r) => r[\"engine\"] == \"raw\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"engine\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TPS\")\r\n  |> filter(fn: (r) => r[\"engine\"] == \"raw\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "TPS usage percentage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 15, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "total_number = () => {\r\n  row = from(bucket: \"${bucketName}\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"engine\")\r\n    |> filter(fn: (r) => r[\"value\"] == \"range\")\r\n    |> count()  \r\n    |> last() \r\n    |> findRecord(fn: (key) => true, idx:0)\r\n  return float(v: row._value)\r\n    \r\n}\r\n\r\n\r\nfrom(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"engine\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TPS\" and r[\"value\"] == \"range\")\r\n  |> duplicate(column: \"_value\", as: \"new_column\")\r\n  |> group(columns: [\"new_column\"])\r\n  |> count()\r\n  |> map(fn: (r) => ({r with _value: float(v: r._value) /total_number() * 100.0}))"
    }
   ]
  }
 ]
}