{
 "title": "2024-03-03 Lap Comparator",
 "tags": [
  "PGR_07",
  "Pszczółki"
 ],
 "time": { "from": "2024-03-03T06:00:00.000Z", "to": "2024-03-03T16:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "bucketName", "query": "telemetry-2023-11-05" },
   { "name": "lap1", "label": "first lap number", "query": "1" },
   { "name": "lap2", "label": "second lap number", "query": "1" },
   { "name": "bucketName2", "query": "telemetry-2024-03-03" }
  ]
 },
 "panels": [
  {
   "title": "First Lap Map",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName2}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap1}), stop: getFinishTime(lapNumber: ${lap1}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gps\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"gps_position\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Second Lap Map",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 14, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\ngetStartTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nstart_time = getStartTime(lapNumber: ${lap1})\r\nstart_time2 = getStartTime(lapNumber: ${lap2})\r\n\r\nhour1 = date.hour(t: start_time)\r\nminute1 = date.minute(t: start_time)\r\nsecond1 = date.second(t: start_time)\r\n\r\nhour2 = date.hour(t: start_time2)\r\nminute2 = date.minute(t: start_time2)\r\nsecond2 = date.second(t: start_time2)\r\n\r\nhours = hour2 - hour1\r\nminutes = minute2 - minute1\r\nseconds = second2 - second1\r\ntotal_sec = hours * 3600 + minutes * 60 + seconds\r\nsecondos = total_sec * 1000000000\r\ntest2 = duration(v: uint(v: secondos))\r\n\r\nfrom(bucket: \"${bucketName2}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap2}), stop: getFinishTime(lapNumber: ${lap2}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gps\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"gps_position\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> timeShift(duration: -test2)\r\n"
    }
   ]
  },
  {
   "title": "First Lap - Speed [km/h]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName2}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap1}), stop: getFinishTime(lapNumber: ${lap1}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"spd\")\r\n  |> filter(fn: (r) => r[\"Record\"] == \"velocity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Second Lap - Speed [km/h]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\ngetStartTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nstart_time = getStartTime(lapNumber: ${lap1})\r\nstart_time2 = getStartTime(lapNumber: ${lap2})\r\n\r\nhour1 = date.hour(t: start_time)\r\nminute1 = date.minute(t: start_time)\r\nsecond1 = date.second(t: start_time)\r\n\r\nhour2 = date.hour(t: start_time2)\r\nminute2 = date.minute(t: start_time2)\r\nsecond2 = date.second(t: start_time2)\r\n\r\nhours = hour2 - hour1\r\nminutes = minute2 - minute1\r\nseconds = second2 - second1\r\ntotal_sec = hours * 3600 + minutes * 60 + seconds\r\nsecondos = total_sec * 1000000000\r\ntest2 = duration(v: uint(v: secondos))\r\n\r\nfrom(bucket: \"${bucketName2}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap2}), stop: getFinishTime(lapNumber: ${lap2}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"spd\")\r\n  |> filter(fn: (r) => r[\"Record\"] == \"velocity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)\r\n  |> timeShift(duration: -test2)"
    }
   ]
  },
  {
   "title": "First Lap - Acceleration [m/s^2]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "m/s^2" } },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName2}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap1}), stop: getFinishTime(lapNumber: ${lap1}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"acc\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"acc_x\" or r[\"_field\"] == \"acc_y\" or r[\"_field\"] == \"acc_z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Second Lap - Acceleration [m/s^2]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "m/s^2" } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\ngetStartTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nstart_time = getStartTime(lapNumber: ${lap1})\r\nstart_time2 = getStartTime(lapNumber: ${lap2})\r\n\r\nhour1 = date.hour(t: start_time)\r\nminute1 = date.minute(t: start_time)\r\nsecond1 = date.second(t: start_time)\r\n\r\nhour2 = date.hour(t: start_time2)\r\nminute2 = date.minute(t: start_time2)\r\nsecond2 = date.second(t: start_time2)\r\n\r\nhours = hour2 - hour1\r\nminutes = minute2 - minute1\r\nseconds = second2 - second1\r\ntotal_sec = hours * 3600 + minutes * 60 + seconds\r\n\r\nsecondos = total_sec * 1000000000\r\ntest2 = duration(v: uint(v: secondos))\r\n\r\nfrom(bucket: \"${bucketName2}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap2}), stop: getFinishTime(lapNumber: ${lap2}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"acc\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"acc_x\" or r[\"_field\"] == \"acc_y\" or r[\"_field\"] == \"acc_z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)\r\n  |> timeShift(duration: -test2)"
    }
   ]
  },
  {
   "title": "First Lap - Gyroscope [deg/s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "rotdegs" } },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName2}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap1}), stop: getFinishTime(lapNumber: ${lap1}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gyro\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gyro_x\" or r[\"_field\"] == \"gyro_y\" or r[\"_field\"] == \"gyro_z\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Second Lap - Gyroscope [deg/s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "rotdegs" } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\ngetStartTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nstart_time = getStartTime(lapNumber: ${lap1})\r\nstart_time2 = getStartTime(lapNumber: ${lap2})\r\n\r\nhour1 = date.hour(t: start_time)\r\nminute1 = date.minute(t: start_time)\r\nsecond1 = date.second(t: start_time)\r\n\r\nhour2 = date.hour(t: start_time2)\r\nminute2 = date.minute(t: start_time2)\r\nsecond2 = date.second(t: start_time2)\r\n\r\nhours = hour2 - hour1\r\nminutes = minute2 - minute1\r\nseconds = second2 - second1\r\ntotal_sec = hours * 3600 + minutes * 60 + seconds\r\n\r\nsecondos = total_sec * 1000000000\r\ntest2 = duration(v: uint(v: secondos))\r\n\r\nfrom(bucket: \"${bucketName2}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap2}), stop: getFinishTime(lapNumber: ${lap2}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gyro\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gyro_x\" or r[\"_field\"] == \"gyro_y\" or r[\"_field\"] == \"gyro_z\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)\r\n  |> timeShift(duration: -test2)"
    }
   ]
  },
  {
   "title": "First Lap - Angular Acceleration [deg/s^2]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "deg/s^2" } },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName2}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap1}), stop: getFinishTime(lapNumber: ${lap1}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"angular_acc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ang_acc_x\" or r[\"_field\"] == \"ang_acc_y\" or r[\"_field\"] == \"ang_acc_z\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Second Lap - Angular Acceleration [deg/s^2]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "deg/s^2" } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\ngetStartTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nstart_time = getStartTime(lapNumber: ${lap1})\r\nstart_time2 = getStartTime(lapNumber: ${lap2})\r\n\r\nhour1 = date.hour(t: start_time)\r\nminute1 = date.minute(t: start_time)\r\nsecond1 = date.second(t: start_time)\r\n\r\nhour2 = date.hour(t: start_time2)\r\nminute2 = date.minute(t: start_time2)\r\nsecond2 = date.second(t: start_time2)\r\n\r\nhours = hour2 - hour1\r\nminutes = minute2 - minute1\r\nseconds = second2 - second1\r\ntotal_sec = hours * 3600 + minutes * 60 + seconds\r\n\r\nsecondos = total_sec * 1000000000\r\ntest2 = duration(v: uint(v: secondos))\r\n\r\nfrom(bucket: \"${bucketName2}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap2}), stop: getFinishTime(lapNumber: ${lap2}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"angular_acc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ang_acc_x\" or r[\"_field\"] == \"ang_acc_y\" or r[\"_field\"] == \"ang_acc_z\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)\r\n  |> timeShift(duration: -test2)"
    }
   ]
  },
  {
   "title": "First Lap - Rotation angles [deg]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName2}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap1}), stop: getFinishTime(lapNumber: ${lap1}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"angles\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pitch_angle\" or r[\"_field\"] == \"roll_angle\" or r[\"_field\"] == \"yaw_angle\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Second Lap - Rotation angles [deg]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\ngetStartTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nstart_time = getStartTime(lapNumber: ${lap1})\r\nstart_time2 = getStartTime(lapNumber: ${lap2})\r\n\r\nhour1 = date.hour(t: start_time)\r\nminute1 = date.minute(t: start_time)\r\nsecond1 = date.second(t: start_time)\r\n\r\nhour2 = date.hour(t: start_time2)\r\nminute2 = date.minute(t: start_time2)\r\nsecond2 = date.second(t: start_time2)\r\n\r\nhours = hour2 - hour1\r\nminutes = minute2 - minute1\r\nseconds = second2 - second1\r\ntotal_sec = hours * 3600 + minutes * 60 + seconds\r\n\r\nsecondos = total_sec * 1000000000\r\ntest2 = duration(v: uint(v: secondos))\r\n\r\nfrom(bucket: \"${bucketName2}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap2}), stop: getFinishTime(lapNumber: ${lap2}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"angles\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pitch_angle\" or r[\"_field\"] == \"roll_angle\" or r[\"_field\"] == \"yaw_angle\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)\r\n  |> timeShift(duration: -test2)"
    }
   ]
  },
  {
   "title": "First Lap - Velocity [km/h]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName2}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap1}), stop: getFinishTime(lapNumber: ${lap1}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vel_acc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vel_x\" or r[\"_field\"] == \"vel_y\" or r[\"_field\"] == \"vel_z\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Second Lap - Velocity [km/h]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\ngetStartTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"${bucketName2}\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nstart_time = getStartTime(lapNumber: ${lap1})\r\nstart_time2 = getStartTime(lapNumber: ${lap2})\r\n\r\nhour1 = date.hour(t: start_time)\r\nminute1 = date.minute(t: start_time)\r\nsecond1 = date.second(t: start_time)\r\n\r\nhour2 = date.hour(t: start_time2)\r\nminute2 = date.minute(t: start_time2)\r\nsecond2 = date.second(t: start_time2)\r\n\r\nhours = hour2 - hour1\r\nminutes = minute2 - minute1\r\nseconds = second2 - second1\r\ntotal_sec = hours * 3600 + minutes * 60 + seconds\r\n\r\nsecondos = total_sec * 1000000000\r\ntest2 = duration(v: uint(v: secondos))\r\n\r\nfrom(bucket: \"${bucketName2}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap2}), stop: getFinishTime(lapNumber: ${lap2}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vel_acc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vel_x\" or r[\"_field\"] == \"vel_y\" or r[\"_field\"] == \"vel_z\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)\r\n  |> timeShift(duration: -test2)"
    }
   ]
  }
 ]
}