{
 "title": "2024-03-17 cooling system,ecumaster",
 "tags": [
  "PGR_07",
  "Pszczółki"
 ],
 "time": { "from": "2024-03-17T09:28:07.636Z", "to": "2024-03-17T11:10:58.184Z" },
 "templating": {
  "list": [
   { "name": "bucketName", "query": "${VAR_BUCKETNAME}" }
  ]
 },
 "panels": [
  {
   "title": "Engine and Radiators Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"in\" or r[\"_field\"] == \"out\")\r\n  |> filter(fn: (r) => r[\"temperature\"] == \"engine\" or r[\"temperature\"] == \"radiator_l\" or r[\"temperature\"] == \"radiator_r\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Engine and Radiator Temperature Delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"delta\")\r\n  |> filter(fn: (r) => r[\"temperature\"] == \"engine\" or r[\"temperature\"] == \"radiator_l\" or r[\"temperature\"] == \"radiator_r\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Temperature Rise Velocity [°C/min]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "°C/min" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"in_delta\" or r[\"_field\"] == \"out_delta\")\r\n  |> filter(fn: (r) => r[\"temperature\"] == \"engine\" or r[\"temperature\"] == \"radiator_l\" or r[\"temperature\"] == \"radiator_r\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Heat to cooling system [kJ/s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kJ/s" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"engine\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"heat_from_engine\" or r[\"_field\"] == \"heat_theoretical\")\r\n  |> filter(fn: (r) => r[\"engine\"] == \"heat\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Engine RPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"engine\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RPM\")\r\n  |> filter(fn: (r) => r[\"engine\"] == \"raw\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Coolant fan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"engine\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Coolant fan\")\r\n  |> filter(fn: (r) => r[\"engine\"] == \"raw\")\r\n  |> aggregateWindow(every: $__interval, fn: max)\r\n  |> map(fn: (r) => ({ r with _value: r._value == 1 }))"
    }
   ]
  },
  {
   "title": "Oil temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"engine\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temp\")\r\n  |> filter(fn: (r) => r[\"oil\"] == \"raw\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "CLT",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"engine\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"clt\")\r\n  |> filter(fn: (r) => r[\"ecumaster\"] == \"raw\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "MAP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"engine\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"MAP\")\r\n  |> filter(fn: (r) => r[\"engine\"] == \"raw\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "TPS usage percentage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "total_number = () => {\r\n  row = from(bucket: \"${bucketName}\")\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => r[\"_measurement\"] == \"engine\")\r\n    |> filter(fn: (r) => r[\"value\"] == \"range\")\r\n    |> count()  \r\n    |> last() \r\n    |> findRecord(fn: (key) => true, idx:0)\r\n  return float(v: row._value)\r\n    \r\n}\r\n\r\n\r\nfrom(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"engine\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TPS\" and r[\"value\"] == \"range\")\r\n  |> duplicate(column: \"_value\", as: \"new_column\")\r\n  |> group(columns: [\"new_column\"])\r\n  |> count()\r\n  |> map(fn: (r) => ({r with _value: float(v: r._value) /total_number() * 100.0}))\r\n"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucketName}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"engine\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"TPS\")\r\n  |> filter(fn: (r) => r[\"engine\"] == \"raw\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  }
 ]
}