{
 "title": "Lap comparator 2023-11-05",
 "time": { "from": "2023-11-05T08:02:13.078Z", "to": "2023-11-05T08:43:28.135Z" },
 "templating": {
  "list": [
   { "name": "TimeShift", "query": "120s" },
   { "name": "bucketName", "query": "telemetry-2023-11-05" },
   { "name": "lap1", "label": "first lap number", "query": "15" },
   { "name": "lap2", "label": "second lap number", "query": "2" },
   {
    "name": "start_time",
    "query": "start_time_row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._value == int(v: ${lap1}))\r\n  |> first()\r\n  |> keep(columns: [\"_time\"])\r\n  |> findRecord(idx: 0, fn: (key) => true)"
   },
   {
    "name": "finish_time",
    "query": "finish_time_row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._value == int(v: ${lap1}))\r\n  |> last()\r\n  |> keep(columns: [\"_time\"])\r\n  |> findRecord(idx: 0, fn: (key) => true)"
   },
   { "name": "bucketName2", "query": "telemetry-2023-11-05-Racebox" }
  ]
 },
 "panels": [
  {
   "title": "First Lap Map",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: getStartTime(lapNumber: ${lap1}), stop: getFinishTime(lapNumber: ${lap1}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gps\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"gps_position\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Second Lap Map",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 14, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: getStartTime(lapNumber: ${lap2}), stop: getFinishTime(lapNumber: ${lap2}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gps\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"gps_position\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "First lap - suspension travel [mm]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap1}), stop: getFinishTime(lapNumber: ${lap1}))\r\n  |> filter(fn: (r) => r[\"ID\"] == \"7\" or r[\"ID\"] == \"8\" or r[\"ID\"] == \"11\" or r[\"ID\"] == \"12\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"angle\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Second lap - suspension travel [mm] ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap2}), stop: getFinishTime(lapNumber: ${lap2}))\r\n  |> filter(fn: (r) => r[\"ID\"] == \"7\" or r[\"ID\"] == \"8\" or r[\"ID\"] == \"11\" or r[\"ID\"] == \"12\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"angle\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "First lap - suspension travel [mm/s] ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "mm/s" } },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap1}), stop: getFinishTime(lapNumber: ${lap1}))\r\n  |> filter(fn: (r) => r[\"ID\"] == \"7\" or r[\"ID\"] == \"8\" or r[\"ID\"] == \"11\" or r[\"ID\"] == \"12\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"velocity\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Second lap - suspension travel [mm/s] ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "mm/s" } },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap2}), stop: getFinishTime(lapNumber: ${lap2}))\r\n  |> filter(fn: (r) => r[\"ID\"] == \"7\" or r[\"ID\"] == \"8\" or r[\"ID\"] == \"11\" or r[\"ID\"] == \"12\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"velocity\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "First Lap - Steering wheel angle [deg]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap1}), stop: getFinishTime(lapNumber: ${lap1}))\r\n  |> filter(fn: (r) => r[\"ID\"] == \"6\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"angle\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Second Lap - Steering wheel angle [deg]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap2}), stop: getFinishTime(lapNumber: ${lap2}))\r\n  |> filter(fn: (r) => r[\"ID\"] == \"6\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"angle\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "First Lap - Speed [kmph]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap1}), stop: getFinishTime(lapNumber: ${lap1}))\r\n\t|> filter(fn: (r) => r[\"_measurement\"] == \"gps\" or r[\"_measurement\"] == \"abs\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"gps_position\" or r[\"ID\"] == \"5\" or r[\"ID\"] == \"4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Second Lap - Speed [kmph]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap2}), stop: getFinishTime(lapNumber: ${lap2}))\r\n\t|> filter(fn: (r) => r[\"_measurement\"] == \"gps\" or r[\"_measurement\"] == \"abs\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"gps_position\" or r[\"ID\"] == \"5\" or r[\"ID\"] == \"4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "First Lap - Speed [km/h]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName2}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap1}), stop: getFinishTime(lapNumber: ${lap1}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"spd\")\r\n  |> filter(fn: (r) => r[\"Record\"] == \"velocity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Second Lap - Speed [km/h]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName2}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap2}), stop: getFinishTime(lapNumber: ${lap2}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"spd\")\r\n  |> filter(fn: (r) => r[\"Record\"] == \"velocity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "First Lap - Acceleration [m/s^2]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "m/s^2" } },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName2}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap1}), stop: getFinishTime(lapNumber: ${lap1}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"acc\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"acc_x\" or r[\"_field\"] == \"acc_y\" or r[\"_field\"] == \"acc_z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Second Lap - Acceleration [m/s^2]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "m/s^2" } },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName2}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap2}), stop: getFinishTime(lapNumber: ${lap2}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"acc\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"acc_x\" or r[\"_field\"] == \"acc_y\" or r[\"_field\"] == \"acc_z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "First Lap - Gyroscope [deg/s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "rotdegs" } },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName2}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap1}), stop: getFinishTime(lapNumber: ${lap1}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gyro\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gyro_x\" or r[\"_field\"] == \"gyro_y\" or r[\"_field\"] == \"gyro_z\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Second Lap - Gyroscope [deg/s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "rotdegs" } },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName2}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap2}), stop: getFinishTime(lapNumber: ${lap2}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gyro\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gyro_x\" or r[\"_field\"] == \"gyro_y\" or r[\"_field\"] == \"gyro_z\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "First Lap - Angular Acceleration [deg/s^2]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "deg/s^2" } },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName2}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap1}), stop: getFinishTime(lapNumber: ${lap1}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"angular_acc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ang_acc_x\" or r[\"_field\"] == \"ang_acc_y\" or r[\"_field\"] == \"ang_acc_z\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Second Lap - Angular Acceleration [deg/s^2]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "deg/s^2" } },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName2}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap2}), stop: getFinishTime(lapNumber: ${lap2}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"angular_acc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ang_acc_x\" or r[\"_field\"] == \"ang_acc_y\" or r[\"_field\"] == \"ang_acc_z\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "First Lap - Rotation angles [deg]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName2}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap1}), stop: getFinishTime(lapNumber: ${lap1}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"angles\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pitch_angle\" or r[\"_field\"] == \"roll_angle\" or r[\"_field\"] == \"yaw_angle\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Second Lap - Rotation angles [deg]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName2}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap2}), stop: getFinishTime(lapNumber: ${lap2}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"angles\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pitch_angle\" or r[\"_field\"] == \"roll_angle\" or r[\"_field\"] == \"yaw_angle\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "First Lap - Velocity [km/h]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName2}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap1}), stop: getFinishTime(lapNumber: ${lap1}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vel_acc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vel_x\" or r[\"_field\"] == \"vel_y\" or r[\"_field\"] == \"vel_z\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Second Lap - Velocity [km/h]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "getStartTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> first()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\ngetFinishTime = (lapNumber) => {\r\n    row = from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n        |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n        |> filter(fn: (r) => r[\"lap_time\"] == \"lap_number\")\r\n        |> filter(fn: (r) => r._value == int(v: lapNumber))\r\n        |> group()\r\n        |> last()\r\n        |> findRecord(fn: (key) => true, idx:0)\r\n    return row._time\r\n}\r\n\r\nfrom(bucket: \"${bucketName2}\")\r\n  |> range(start: getStartTime(lapNumber: ${lap2}), stop: getFinishTime(lapNumber: ${lap2}))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vel_acc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vel_x\" or r[\"_field\"] == \"vel_y\" or r[\"_field\"] == \"vel_z\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  }
 ]
}