{
 "title": "Telemetry 2023-11-05",
 "time": { "from": "2023-11-05T09:47:18.427Z", "to": "2023-11-05T09:49:09.932Z" },
 "templating": {
  "list": [
   { "name": "bucketName", "query": "telemetry-2023-11-05" }
  ]
 },
 "panels": [
  {
   "title": "Map",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 23, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gps\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"gps_position\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Timer",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lap_times\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"best_time\" or r[\"_field\"] == \"current_time\" or r[\"_field\"] == \"lap_counter\" or r[\"_field\"] == \"last_time\")\r\n  |> filter(fn: (r) => r[\"lap_time\"] == \"best\" or r[\"lap_time\"] == \"lap_number\" or r[\"lap_time\"] == \"last\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Timer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"lap_times\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"best_time\" or r[\"_field\"] == \"current_time\" or r[\"_field\"] == \"lap_counter\" or r[\"_field\"] == \"last_time\")\r\n  |> filter(fn: (r) => r[\"lap_time\"] == \"best\" or r[\"lap_time\"] == \"lap_number\" or r[\"lap_time\"] == \"last\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Steering wheel angle [deg]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"6\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"angle\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Acceleration [m/s^2]",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"acc\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"acc_x\" or r[\"_field\"] == \"acc_y\" or r[\"_field\"] == \"acc_z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Dampers - suspension travel [mm]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 10, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"ID\"] == \"7\" or r[\"ID\"] == \"8\" or r[\"ID\"] == \"11\" or r[\"ID\"] == \"12\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"angle\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Angular velocity [deg/s]",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "rotdegs" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gyro\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gyro_x\" or r[\"_field\"] == \"gyro_y\" or r[\"_field\"] == \"gyro_z\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Dampers - suspension travel speed [mm/s]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 10, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "mm/s" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"ID\"] == \"7\" or r[\"ID\"] == \"8\" or r[\"ID\"] == \"11\" or r[\"ID\"] == \"12\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"damp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"velocity\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Angular acceleration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "°/sec^2" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"angular_acc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ang_acc_x\" or r[\"_field\"] == \"ang_acc_y\" or r[\"_field\"] == \"ang_acc_z\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Speed [kmph]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gps\" or r[\"_measurement\"] == \"abs\")\r\n  |> filter(fn: (r) => r[\"ID\"] == \"gps_position\" or r[\"ID\"] == \"5\" or r[\"ID\"] == \"4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Speed [km/h]",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 10, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"spd\")\r\n  |> filter(fn: (r) => r[\"Record\"] == \"velocity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")\r\n  |> aggregateWindow(every: $__interval, fn: mean)"
    }
   ]
  },
  {
   "title": "Rotation angles",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"angles\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pitch_angle\" or r[\"_field\"] == \"roll_angle\" or r[\"_field\"] == \"yaw_angle\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Velocity ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 10, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry-2023-11-05-Racebox\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vel_acc\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"vel_x\" or r[\"_field\"] == \"vel_y\" or r[\"_field\"] == \"vel_z\")\r\n  |> filter(fn: (r) => r[\"axis\"] == \"x\" or r[\"axis\"] == \"y\" or r[\"axis\"] == \"z\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  }
 ]
}